# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adminpanel.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from BusinessLogic.Advisee import Advisee
from BusinessLogic.PeerAdviser import PeerAdviser
from BusinessLogic.Admin import Admin

class Ui_AdminPanel(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(801, 550)
        self.admin_panel = QtWidgets.QGroupBox(Dialog)
        self.admin_panel.setGeometry(QtCore.QRect(10, 90, 121, 451))
        self.admin_panel.setTitle("")
        self.admin_panel.setObjectName("admin_panel")
        self.pushButton_viewStudentInfo = QtWidgets.QPushButton(self.admin_panel)
        self.pushButton_viewStudentInfo.setGeometry(QtCore.QRect(10, 40, 101, 41))
        self.pushButton_viewStudentInfo.setAutoExclusive(True)
        self.pushButton_viewStudentInfo.setObjectName("pushButton_viewStudentInfo")
        self.pushButton_viewStudentInfo.clicked.connect(lambda: self.push_vsi())
        self.pushButton_viewSessionLog = QtWidgets.QPushButton(self.admin_panel)
        self.pushButton_viewSessionLog.setGeometry(QtCore.QRect(10, 80, 101, 41))
        self.pushButton_viewSessionLog.setAutoExclusive(True)
        self.pushButton_viewSessionLog.setObjectName("pushButton_viewSessionLog")
        self.pushButton_viewSessionLog.clicked.connect(lambda: self.push_vsl())
        self.pushButton_viewTimeSheetLog = QtWidgets.QPushButton(self.admin_panel)
        self.pushButton_viewTimeSheetLog.setGeometry(QtCore.QRect(10, 120, 101, 41))
        self.pushButton_viewTimeSheetLog.setAutoExclusive(True)
        self.pushButton_viewTimeSheetLog.setObjectName("pushButton_viewTimeSheetLog")
        self.pushButton_viewTimeSheetLog.clicked.connect(lambda: self.push_vts())
        self.pushButton_add = QtWidgets.QPushButton(self.admin_panel)
        self.pushButton_add.setGeometry(QtCore.QRect(10, 160, 101, 41))
        self.pushButton_add.setAutoExclusive(True)
        self.pushButton_add.setObjectName("pushButton_add")
        self.pushButton_add.clicked.connect(lambda:self.push_add())
        self.pushButton_modify = QtWidgets.QPushButton(self.admin_panel)
        self.pushButton_modify.setGeometry(QtCore.QRect(10, 200, 101, 41))
        self.pushButton_modify.setAutoExclusive(True)
        self.pushButton_modify.setObjectName("pushButton_modify")
        self.pushButton_modify.clicked.connect(lambda:self.push_modify())
        self.pushButton_email = QtWidgets.QPushButton(self.admin_panel)
        self.pushButton_email.setGeometry(QtCore.QRect(10, 240, 101, 41))
        self.pushButton_email.setAutoExclusive(True)
        self.pushButton_email.setObjectName("pushButton_email")
        self.pushButton_email.clicked.connect(lambda:self.push_email())
        self.pushButton_viewEvaluation = QtWidgets.QPushButton(self.admin_panel)
        self.pushButton_viewEvaluation.setGeometry(QtCore.QRect(10, 280, 101, 41))
        self.pushButton_viewEvaluation.setAutoExclusive(True)
        self.pushButton_viewEvaluation.setObjectName("pushButton_viewEvaluation")
        self.pushButton_viewEvaluation.clicked.connect(lambda:self.push_ve())
        self.pushButton_clearDatabase = QtWidgets.QPushButton(self.admin_panel)
        self.pushButton_clearDatabase.setGeometry(QtCore.QRect(10, 400, 101, 41))
        self.pushButton_clearDatabase.setAutoExclusive(True)
        self.pushButton_clearDatabase.setObjectName("pushButton_clearDatabase")
        self.label_adminPanel = QtWidgets.QLabel(self.admin_panel)
        self.label_adminPanel.setGeometry(QtCore.QRect(10, 10, 101, 16))
        self.label_adminPanel.setAlignment(QtCore.Qt.AlignCenter)
        self.label_adminPanel.setObjectName("label_adminPanel")
        
        self.vsi_panel = QtWidgets.QGroupBox(Dialog)
        self.vsi_panel.setGeometry(QtCore.QRect(140, 90, 651, 451))
        self.vsi_panel.setTitle("")
        self.vsi_panel.setObjectName("vsi_panel")
        self.radioButton_vsi_advisee = QtWidgets.QRadioButton(self.vsi_panel)
        self.radioButton_vsi_advisee.setGeometry(QtCore.QRect(50, 40, 91, 17))
        self.radioButton_vsi_advisee.setObjectName("radioButton_vsi_advisee")
        self.radioButton_vsi_advisee.setChecked(True)
        self.radioButton_vsi_advisee.toggled.connect(lambda: self.toggle_vsia())
        self.radioButton_vsi_peeradviser = QtWidgets.QRadioButton(self.vsi_panel)
        self.radioButton_vsi_peeradviser.setGeometry(QtCore.QRect(150, 40, 91, 17))
        self.radioButton_vsi_peeradviser.setObjectName("radioButton_vsi_peeradviser")
        self.radioButton_vsi_advisee.toggled.connect(lambda: self.toggle_vsip())
        self.lineEdit_vsi_studentnumber = QtWidgets.QLineEdit(self.vsi_panel)
        self.lineEdit_vsi_studentnumber.setGeometry(QtCore.QRect(52, 70, 109, 21))
        self.lineEdit_vsi_studentnumber.setObjectName("lineEdit_vsi_studentnumber")
        self.lineEdit_vsi_studentnumber.returnPressed.connect(lambda: self.push_vsi_search())
        self.lineEdit_vsi_studentnumber.textChanged.connect(lambda: self.vsi_clear())
        self.pushButton_vsi_search = QtWidgets.QPushButton(self.vsi_panel)
        self.pushButton_vsi_search.setEnabled(True)
        self.pushButton_vsi_search.setGeometry(QtCore.QRect(160, 69, 51, 23))
        self.pushButton_vsi_search.setObjectName("pushButton_vsi_search")
        self.pushButton_vsi_search.clicked.connect(lambda: self.push_vsi_search())
        self.groupBox_vsia = QtWidgets.QGroupBox(self.vsi_panel)
        self.groupBox_vsia.setEnabled(True)
        self.groupBox_vsia.setGeometry(QtCore.QRect(30, 120, 591, 131))
        self.groupBox_vsia.setObjectName("groupBox_vsia")
        self.xx_3 = QtWidgets.QLabel(self.groupBox_vsia)
        self.xx_3.setGeometry(QtCore.QRect(10, 100, 111, 16))
        self.xx_3.setObjectName("xx_3")
        self.xx = QtWidgets.QLabel(self.groupBox_vsia)
        self.xx.setGeometry(QtCore.QRect(10, 20, 51, 16))
        self.xx.setObjectName("xx")
        self.xx_2 = QtWidgets.QLabel(self.groupBox_vsia)
        self.xx_2.setGeometry(QtCore.QRect(10, 40, 51, 16))
        self.xx_2.setObjectName("xx_2")
        self.xx_4 = QtWidgets.QLabel(self.groupBox_vsia)
        self.xx_4.setGeometry(QtCore.QRect(10, 80, 111, 16))
        self.xx_4.setObjectName("xx_4")
        self.xx_5 = QtWidgets.QLabel(self.groupBox_vsia)
        self.xx_5.setGeometry(QtCore.QRect(10, 60, 111, 16))
        self.xx_5.setObjectName("xx_5")
        self.label_vsia_name = QtWidgets.QLabel(self.groupBox_vsia)
        self.label_vsia_name.setGeometry(QtCore.QRect(110, 20, 200, 16))
        self.label_vsia_name.setText("")
        self.label_vsia_name.setObjectName("label_vsia_name")
        self.label_vsia_program = QtWidgets.QLabel(self.groupBox_vsia)
        self.label_vsia_program.setGeometry(QtCore.QRect(110, 40, 200, 16))
        self.label_vsia_program.setText("")
        self.label_vsia_program.setObjectName("label_vsia_program")
        self.label_vsia_contactnumber = QtWidgets.QLabel(self.groupBox_vsia)
        self.label_vsia_contactnumber.setGeometry(QtCore.QRect(110, 60, 200, 16))
        self.label_vsia_contactnumber.setText("")
        self.label_vsia_contactnumber.setObjectName("label_vsia_contactnumber")
        self.label_vsia_emailaddress = QtWidgets.QLabel(self.groupBox_vsia)
        self.label_vsia_emailaddress.setGeometry(QtCore.QRect(110, 80, 200, 16))
        self.label_vsia_emailaddress.setText("")
        self.label_vsia_emailaddress.setObjectName("label_vsia_emailaddress")
        self.label_vsia_homeaddress = QtWidgets.QLabel(self.groupBox_vsia)
        self.label_vsia_homeaddress.setGeometry(QtCore.QRect(110, 100, 200, 16))
        self.label_vsia_homeaddress.setText("")
        self.label_vsia_homeaddress.setObjectName("label_vsia_homeaddress")
        self.xx_3.raise_()
        self.xx.raise_()
        self.xx_2.raise_()
        self.xx_4.raise_()
        self.xx_5.raise_()
        self.label_vsia_name.raise_()
        self.label_vsia_program.raise_()
        self.label_vsia_contactnumber.raise_()
        self.label_vsia_emailaddress.raise_()
        self.label_vsia_homeaddress.raise_()
        self.groupBox_vsip = QtWidgets.QGroupBox(self.vsi_panel)
        self.groupBox_vsip.setGeometry(QtCore.QRect(30, 120, 591, 161))
        self.groupBox_vsip.setObjectName("groupBox_vsip")
        self.groupBox_vsip.setVisible(False)
        self.xx_7 = QtWidgets.QLabel(self.groupBox_vsip)
        self.xx_7.setGeometry(QtCore.QRect(10, 20, 51, 16))
        self.xx_7.setObjectName("xx_7")
        self.xx_8 = QtWidgets.QLabel(self.groupBox_vsip)
        self.xx_8.setGeometry(QtCore.QRect(10, 40, 51, 16))
        self.xx_8.setObjectName("xx_8")
        self.xx_9 = QtWidgets.QLabel(self.groupBox_vsip)
        self.xx_9.setGeometry(QtCore.QRect(10, 80, 111, 16))
        self.xx_9.setObjectName("xx_9")
        self.xx_10 = QtWidgets.QLabel(self.groupBox_vsip)
        self.xx_10.setGeometry(QtCore.QRect(10, 60, 111, 16))
        self.xx_10.setObjectName("xx_10")
        self.label_vsip_name = QtWidgets.QLabel(self.groupBox_vsip)
        self.label_vsip_name.setGeometry(QtCore.QRect(110, 20, 200, 16))
        self.label_vsip_name.setText("")
        self.label_vsip_name.setObjectName("label_vsip_name")
        self.label_vsip_program = QtWidgets.QLabel(self.groupBox_vsip)
        self.label_vsip_program.setGeometry(QtCore.QRect(110, 40, 200, 16))
        self.label_vsip_program.setText("")
        self.label_vsip_program.setObjectName("label_vsip_program")
        self.label_vsip_contactnumber = QtWidgets.QLabel(self.groupBox_vsip)
        self.label_vsip_contactnumber.setGeometry(QtCore.QRect(110, 60, 200, 16))
        self.label_vsip_contactnumber.setText("")
        self.label_vsip_contactnumber.setObjectName("label_vsip_contactnumber")
        self.label_vsip_organization = QtWidgets.QLabel(self.groupBox_vsip)
        self.label_vsip_organization.setGeometry(QtCore.QRect(110, 80, 200, 16))
        self.label_vsip_organization.setText("")
        self.label_vsip_organization.setObjectName("label_vsip_organization")
        self.xx_11 = QtWidgets.QLabel(self.groupBox_vsip)
        self.xx_11.setGeometry(QtCore.QRect(10, 100, 111, 16))
        self.xx_11.setObjectName("xx_11")
        self.label_vsip_advisingschedule_1 = QtWidgets.QLabel(self.groupBox_vsip)
        self.label_vsip_advisingschedule_1.setGeometry(QtCore.QRect(110, 100, 200, 16))
        self.label_vsip_advisingschedule_1.setText("")
        self.label_vsip_advisingschedule_1.setObjectName("label_vsip_advisingschedule_1")
        self.label_vsip_advisingschedule_2 = QtWidgets.QLabel(self.groupBox_vsip)
        self.label_vsip_advisingschedule_2.setGeometry(QtCore.QRect(110, 120, 200, 16))
        self.label_vsip_advisingschedule_2.setText("")
        self.label_vsip_advisingschedule_2.setObjectName("label_vsip_advisingschedule_2")
        self.pushButton_vsi_delete = QtWidgets.QPushButton(self.vsi_panel)
        self.pushButton_vsi_delete.setEnabled(True)
        self.pushButton_vsi_delete.setGeometry(QtCore.QRect(540, 290, 81, 21))
        self.pushButton_vsi_delete.setObjectName("pushButton_vsi_delete")
        self.vsl_panel = QtWidgets.QGroupBox(Dialog)
        self.vsl_panel.setGeometry(QtCore.QRect(140, 90, 651, 451))
        self.vsl_panel.setTitle("")
        self.vsl_panel.setObjectName("vsl_panel")
        self.radioButton_vsl_searchByDate = QtWidgets.QRadioButton(self.vsl_panel)
        self.radioButton_vsl_searchByDate.setGeometry(QtCore.QRect(70, 40, 91, 17))
        self.radioButton_vsl_searchByDate.setObjectName("radioButton_vsl_searchByDate")
        self.radioButton_vsl_searchByStudentNumber = QtWidgets.QRadioButton(self.vsl_panel)
        self.radioButton_vsl_searchByStudentNumber.setGeometry(QtCore.QRect(70, 70, 171, 17))
        self.radioButton_vsl_searchByStudentNumber.setObjectName("radioButton_vsl_searchByStudentNumber")
        self.lineEdit_vsl_studentnumber = QtWidgets.QLineEdit(self.vsl_panel)
        self.lineEdit_vsl_studentnumber.setEnabled(False)
        self.lineEdit_vsl_studentnumber.setGeometry(QtCore.QRect(230, 71, 109, 21))
        self.lineEdit_vsl_studentnumber.setObjectName("lineEdit_vsl_studentnumber")
        self.pushButton_vsl_search = QtWidgets.QPushButton(self.vsl_panel)
        self.pushButton_vsl_search.setEnabled(True)
        self.pushButton_vsl_search.setGeometry(QtCore.QRect(490, 40, 81, 51))
        self.pushButton_vsl_search.setObjectName("pushButton_vsl_search")
        self.dateEdit_vsl = QtWidgets.QDateEdit(self.vsl_panel)
        self.dateEdit_vsl.setEnabled(True)
        self.dateEdit_vsl.setGeometry(QtCore.QRect(230, 41, 109, 22))
        self.dateEdit_vsl.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2018, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit_vsl.setObjectName("dateEdit_vsl")
        self.tableWidget_vslbsn = QtWidgets.QTableWidget(self.vsl_panel)
        self.tableWidget_vslbsn.setGeometry(QtCore.QRect(70, 110, 502, 311))
        self.tableWidget_vslbsn.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_vslbsn.setAlternatingRowColors(True)
        self.tableWidget_vslbsn.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidget_vslbsn.setObjectName("tableWidget_vslbsn")
        self.tableWidget_vslbsn.setColumnCount(5)
        self.tableWidget_vslbsn.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_vslbsn.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_vslbsn.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_vslbsn.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_vslbsn.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_vslbsn.setHorizontalHeaderItem(4, item)
        self.tableWidget_vslbd = QtWidgets.QTableWidget(self.vsl_panel)
        self.tableWidget_vslbd.setGeometry(QtCore.QRect(70, 110, 502, 311))
        self.tableWidget_vslbd.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_vslbd.setAlternatingRowColors(True)
        self.tableWidget_vslbd.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidget_vslbd.setObjectName("tableWidget_vslbd")
        self.tableWidget_vslbd.setColumnCount(5)
        self.tableWidget_vslbd.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_vslbd.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_vslbd.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_vslbd.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_vslbd.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_vslbd.setHorizontalHeaderItem(4, item)
        self.tableWidget_vslbsn.raise_()
        self.tableWidget_vslbd.raise_()
        self.radioButton_vsl_searchByDate.raise_()
        self.radioButton_vsl_searchByStudentNumber.raise_()
        self.lineEdit_vsl_studentnumber.raise_()
        self.pushButton_vsl_search.raise_()
        self.dateEdit_vsl.raise_()
        self.vts_panel = QtWidgets.QGroupBox(Dialog)
        self.vts_panel.setGeometry(QtCore.QRect(140, 90, 651, 451))
        self.vts_panel.setTitle("")
        self.vts_panel.setObjectName("vts_panel")
        self.radioButton_vts_searchByDate = QtWidgets.QRadioButton(self.vts_panel)
        self.radioButton_vts_searchByDate.setGeometry(QtCore.QRect(100, 40, 91, 17))
        self.radioButton_vts_searchByDate.setObjectName("radioButton_vts_searchByDate")
        self.radioButton_vts_searchByStudentNumber = QtWidgets.QRadioButton(self.vts_panel)
        self.radioButton_vts_searchByStudentNumber.setGeometry(QtCore.QRect(100, 70, 171, 17))
        self.radioButton_vts_searchByStudentNumber.setObjectName("radioButton_vts_searchByStudentNumber")
        self.lineEdit_vts_studentnumber = QtWidgets.QLineEdit(self.vts_panel)
        self.lineEdit_vts_studentnumber.setEnabled(False)
        self.lineEdit_vts_studentnumber.setGeometry(QtCore.QRect(270, 71, 109, 21))
        self.lineEdit_vts_studentnumber.setObjectName("lineEdit_vts_studentnumber")
        self.pushButton_vts_search = QtWidgets.QPushButton(self.vts_panel)
        self.pushButton_vts_search.setEnabled(True)
        self.pushButton_vts_search.setGeometry(QtCore.QRect(430, 40, 81, 51))
        self.pushButton_vts_search.setObjectName("pushButton_vts_search")
        self.dateEdit_vts = QtWidgets.QDateEdit(self.vts_panel)
        self.dateEdit_vts.setEnabled(True)
        self.dateEdit_vts.setGeometry(QtCore.QRect(270, 41, 109, 22))
        self.dateEdit_vts.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2018, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit_vts.setObjectName("dateEdit_vts")
        self.tableWidget_vtsbsn = QtWidgets.QTableWidget(self.vts_panel)
        self.tableWidget_vtsbsn.setGeometry(QtCore.QRect(160, 110, 302, 311))
        self.tableWidget_vtsbsn.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_vtsbsn.setAlternatingRowColors(True)
        self.tableWidget_vtsbsn.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidget_vtsbsn.setObjectName("tableWidget_vtsbsn")
        self.tableWidget_vtsbsn.setColumnCount(3)
        self.tableWidget_vtsbsn.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_vtsbsn.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_vtsbsn.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_vtsbsn.setHorizontalHeaderItem(2, item)
        self.tableWidget_vtsbd = QtWidgets.QTableWidget(self.vts_panel)
        self.tableWidget_vtsbd.setGeometry(QtCore.QRect(160, 110, 302, 311))
        self.tableWidget_vtsbd.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_vtsbd.setAlternatingRowColors(True)
        self.tableWidget_vtsbd.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tableWidget_vtsbd.setObjectName("tableWidget_vtsbd")
        self.tableWidget_vtsbd.setColumnCount(3)
        self.tableWidget_vtsbd.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_vtsbd.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_vtsbd.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_vtsbd.setHorizontalHeaderItem(2, item)
        self.add_panel = QtWidgets.QGroupBox(Dialog)
        self.add_panel.setGeometry(QtCore.QRect(140, 90, 651, 451))
        self.add_panel.setTitle("")
        self.add_panel.setObjectName("add_panel")
        self.radioButton_a_peeradviser = QtWidgets.QRadioButton(self.add_panel)
        self.radioButton_a_peeradviser.setGeometry(QtCore.QRect(170, 190, 91, 17))
        self.radioButton_a_peeradviser.setObjectName("radioButton_a_peeradviser")
        self.radioButton_a_admin = QtWidgets.QRadioButton(self.add_panel)
        self.radioButton_a_admin.setGeometry(QtCore.QRect(170, 220, 91, 17))
        self.radioButton_a_admin.setObjectName("radioButton_a_admin")
        self.pushButton_a_register = QtWidgets.QPushButton(self.add_panel)
        self.pushButton_a_register.setEnabled(True)
        self.pushButton_a_register.setGeometry(QtCore.QRect(350, 180, 71, 41))
        self.pushButton_a_register.setObjectName("pushButton_a_register")
        self.radioButton_a_advisee = QtWidgets.QRadioButton(self.add_panel)
        self.radioButton_a_advisee.setGeometry(QtCore.QRect(170, 160, 91, 17))
        self.radioButton_a_advisee.setObjectName("radioButton_a_advisee")
        self.xx_26 = QtWidgets.QLabel(self.add_panel)
        self.xx_26.setGeometry(QtCore.QRect(170, 130, 241, 16))
        self.xx_26.setObjectName("xx_26")
        self.modify_panel = QtWidgets.QGroupBox(Dialog)
        self.modify_panel.setGeometry(QtCore.QRect(140, 90, 651, 451))
        self.modify_panel.setTitle("")
        self.modify_panel.setObjectName("modify_panel")
        self.radioButton_m_peeradviser = QtWidgets.QRadioButton(self.modify_panel)
        self.radioButton_m_peeradviser.setGeometry(QtCore.QRect(160, 50, 91, 17))
        self.radioButton_m_peeradviser.setObjectName("radioButton_m_peeradviser")
        self.pushButton_m_confirm = QtWidgets.QPushButton(self.modify_panel)
        self.pushButton_m_confirm.setEnabled(True)
        self.pushButton_m_confirm.setGeometry(QtCore.QRect(520, 390, 91, 31))
        self.pushButton_m_confirm.setObjectName("pushButton_m_confirm")
        self.radioButton_m_advisee = QtWidgets.QRadioButton(self.modify_panel)
        self.radioButton_m_advisee.setGeometry(QtCore.QRect(50, 50, 91, 17))
        self.radioButton_m_advisee.setObjectName("radioButton_m_advisee")
        self.xx_27 = QtWidgets.QLabel(self.modify_panel)
        self.xx_27.setGeometry(QtCore.QRect(50, 90, 141, 16))
        self.xx_27.setObjectName("xx_27")
        self.lineEdit_m_currentstudentnumber = QtWidgets.QLineEdit(self.modify_panel)
        self.lineEdit_m_currentstudentnumber.setGeometry(QtCore.QRect(180, 90, 111, 20))
        self.lineEdit_m_currentstudentnumber.setObjectName("lineEdit_m_currentstudentnumber")
        self.groupBox_m_modifyp = QtWidgets.QGroupBox(self.modify_panel)
        self.groupBox_m_modifyp.setGeometry(QtCore.QRect(30, 120, 591, 241))
        self.groupBox_m_modifyp.setTitle("")
        self.groupBox_m_modifyp.setObjectName("groupBox_m_modifyp")
        self.checkBox_m_studentnumberp = QtWidgets.QCheckBox(self.groupBox_m_modifyp)
        self.checkBox_m_studentnumberp.setGeometry(QtCore.QRect(30, 50, 111, 17))
        self.checkBox_m_studentnumberp.setObjectName("checkBox_m_studentnumberp")
        self.checkBox_m_namep = QtWidgets.QCheckBox(self.groupBox_m_modifyp)
        self.checkBox_m_namep.setGeometry(QtCore.QRect(30, 20, 70, 17))
        self.checkBox_m_namep.setObjectName("checkBox_m_namep")
        self.checkBox_m_programp = QtWidgets.QCheckBox(self.groupBox_m_modifyp)
        self.checkBox_m_programp.setGeometry(QtCore.QRect(30, 80, 111, 17))
        self.checkBox_m_programp.setObjectName("checkBox_m_programp")
        self.checkBox_m_organizationp = QtWidgets.QCheckBox(self.groupBox_m_modifyp)
        self.checkBox_m_organizationp.setGeometry(QtCore.QRect(30, 110, 91, 17))
        self.checkBox_m_organizationp.setObjectName("checkBox_m_organizationp")
        self.checkBox_m_contactnumberp = QtWidgets.QCheckBox(self.groupBox_m_modifyp)
        self.checkBox_m_contactnumberp.setGeometry(QtCore.QRect(30, 140, 121, 17))
        self.checkBox_m_contactnumberp.setObjectName("checkBox_m_contactnumberp")
        self.lineEdit_m_studentnumberp = QtWidgets.QLineEdit(self.groupBox_m_modifyp)
        self.lineEdit_m_studentnumberp.setEnabled(False)
        self.lineEdit_m_studentnumberp.setGeometry(QtCore.QRect(150, 50, 111, 20))
        self.lineEdit_m_studentnumberp.setObjectName("lineEdit_m_studentnumberp")
        self.checkBox_m_advisingschedule = QtWidgets.QCheckBox(self.groupBox_m_modifyp)
        self.checkBox_m_advisingschedule.setGeometry(QtCore.QRect(30, 170, 121, 17))
        self.checkBox_m_advisingschedule.setObjectName("checkBox_m_advisingschedule")
        self.lineEdit_m_lastnamep = QtWidgets.QLineEdit(self.groupBox_m_modifyp)
        self.lineEdit_m_lastnamep.setEnabled(False)
        self.lineEdit_m_lastnamep.setGeometry(QtCore.QRect(90, 20, 151, 20))
        self.lineEdit_m_lastnamep.setObjectName("lineEdit_m_lastnamep")
        self.lineEdit_m_firstnamep = QtWidgets.QLineEdit(self.groupBox_m_modifyp)
        self.lineEdit_m_firstnamep.setEnabled(False)
        self.lineEdit_m_firstnamep.setGeometry(QtCore.QRect(260, 20, 151, 20))
        self.lineEdit_m_firstnamep.setText("")
        self.lineEdit_m_firstnamep.setObjectName("lineEdit_m_firstnamep")
        self.lineEdit_m_middlenamep = QtWidgets.QLineEdit(self.groupBox_m_modifyp)
        self.lineEdit_m_middlenamep.setEnabled(False)
        self.lineEdit_m_middlenamep.setGeometry(QtCore.QRect(430, 20, 151, 20))
        self.lineEdit_m_middlenamep.setObjectName("lineEdit_m_middlenamep")
        self.lineEdit_m_programp = QtWidgets.QLineEdit(self.groupBox_m_modifyp)
        self.lineEdit_m_programp.setEnabled(False)
        self.lineEdit_m_programp.setGeometry(QtCore.QRect(150, 80, 111, 20))
        self.lineEdit_m_programp.setPlaceholderText("")
        self.lineEdit_m_programp.setObjectName("lineEdit_m_programp")
        self.lineEdit_m_organizationp = QtWidgets.QLineEdit(self.groupBox_m_modifyp)
        self.lineEdit_m_organizationp.setEnabled(False)
        self.lineEdit_m_organizationp.setGeometry(QtCore.QRect(150, 110, 111, 20))
        self.lineEdit_m_organizationp.setPlaceholderText("")
        self.lineEdit_m_organizationp.setObjectName("lineEdit_m_organizationp")
        self.lineEdit_m_contactnumberp = QtWidgets.QLineEdit(self.groupBox_m_modifyp)
        self.lineEdit_m_contactnumberp.setEnabled(False)
        self.lineEdit_m_contactnumberp.setGeometry(QtCore.QRect(150, 140, 111, 20))
        self.lineEdit_m_contactnumberp.setPlaceholderText("")
        self.lineEdit_m_contactnumberp.setObjectName("lineEdit_m_contactnumberp")
        self.comboBox_m_day1 = QtWidgets.QComboBox(self.groupBox_m_modifyp)
        self.comboBox_m_day1.setEnabled(False)
        self.comboBox_m_day1.setGeometry(QtCore.QRect(150, 170, 91, 22))
        self.comboBox_m_day1.setObjectName("comboBox_m_day1")
        self.comboBox_m_day1.addItem("")
        self.comboBox_m_day1.addItem("")
        self.comboBox_m_day1.addItem("")
        self.comboBox_m_day1.addItem("")
        self.comboBox_m_day1.addItem("")
        self.comboBox_m_day1.addItem("")
        self.comboBox_m_time1 = QtWidgets.QComboBox(self.groupBox_m_modifyp)
        self.comboBox_m_time1.setEnabled(False)
        self.comboBox_m_time1.setGeometry(QtCore.QRect(250, 170, 151, 22))
        self.comboBox_m_time1.setObjectName("comboBox_m_time1")
        self.comboBox_m_time1.addItem("")
        self.comboBox_m_time1.addItem("")
        self.comboBox_m_time1.addItem("")
        self.comboBox_m_time1.addItem("")
        self.comboBox_m_time1.addItem("")
        self.comboBox_m_time1.addItem("")
        self.comboBox_m_time1.addItem("")
        self.comboBox_m_time1.addItem("")
        self.comboBox_m_time1.addItem("")
        self.comboBox_m_day2 = QtWidgets.QComboBox(self.groupBox_m_modifyp)
        self.comboBox_m_day2.setEnabled(False)
        self.comboBox_m_day2.setGeometry(QtCore.QRect(150, 200, 91, 22))
        self.comboBox_m_day2.setObjectName("comboBox_m_day2")
        self.comboBox_m_day2.addItem("")
        self.comboBox_m_day2.addItem("")
        self.comboBox_m_day2.addItem("")
        self.comboBox_m_day2.addItem("")
        self.comboBox_m_day2.addItem("")
        self.comboBox_m_day2.addItem("")
        self.comboBox_m_time2 = QtWidgets.QComboBox(self.groupBox_m_modifyp)
        self.comboBox_m_time2.setEnabled(False)
        self.comboBox_m_time2.setGeometry(QtCore.QRect(250, 200, 151, 22))
        self.comboBox_m_time2.setObjectName("comboBox_m_time2")
        self.comboBox_m_time2.addItem("")
        self.comboBox_m_time2.addItem("")
        self.comboBox_m_time2.addItem("")
        self.comboBox_m_time2.addItem("")
        self.comboBox_m_time2.addItem("")
        self.comboBox_m_time2.addItem("")
        self.comboBox_m_time2.addItem("")
        self.comboBox_m_time2.addItem("")
        self.comboBox_m_time2.addItem("")
        self.groupBox_m_modifya = QtWidgets.QGroupBox(self.modify_panel)
        self.groupBox_m_modifya.setGeometry(QtCore.QRect(30, 120, 591, 241))
        self.groupBox_m_modifya.setTitle("")
        self.groupBox_m_modifya.setObjectName("groupBox_m_modifya")
        self.checkBox_m_studentnumbera = QtWidgets.QCheckBox(self.groupBox_m_modifya)
        self.checkBox_m_studentnumbera.setGeometry(QtCore.QRect(30, 50, 111, 17))
        self.checkBox_m_studentnumbera.setObjectName("checkBox_m_studentnumbera")
        self.checkBox_m_namea = QtWidgets.QCheckBox(self.groupBox_m_modifya)
        self.checkBox_m_namea.setGeometry(QtCore.QRect(30, 20, 70, 17))
        self.checkBox_m_namea.setObjectName("checkBox_m_namea")
        self.checkBox_m_programa = QtWidgets.QCheckBox(self.groupBox_m_modifya)
        self.checkBox_m_programa.setGeometry(QtCore.QRect(30, 80, 111, 17))
        self.checkBox_m_programa.setObjectName("checkBox_m_programa")
        self.checkBox_m_emailaddressa = QtWidgets.QCheckBox(self.groupBox_m_modifya)
        self.checkBox_m_emailaddressa.setGeometry(QtCore.QRect(30, 140, 91, 17))
        self.checkBox_m_emailaddressa.setObjectName("checkBox_m_emailaddressa")
        self.checkBox_m_contactnumbera = QtWidgets.QCheckBox(self.groupBox_m_modifya)
        self.checkBox_m_contactnumbera.setGeometry(QtCore.QRect(30, 110, 121, 17))
        self.checkBox_m_contactnumbera.setObjectName("checkBox_m_contactnumbera")
        self.lineEdit_m_studentnumbera = QtWidgets.QLineEdit(self.groupBox_m_modifya)
        self.lineEdit_m_studentnumbera.setEnabled(False)
        self.lineEdit_m_studentnumbera.setGeometry(QtCore.QRect(150, 50, 111, 20))
        self.lineEdit_m_studentnumbera.setObjectName("lineEdit_m_studentnumbera")
        self.checkBox_m_homeaddress = QtWidgets.QCheckBox(self.groupBox_m_modifya)
        self.checkBox_m_homeaddress.setGeometry(QtCore.QRect(30, 170, 121, 17))
        self.checkBox_m_homeaddress.setObjectName("checkBox_m_homeaddress")
        self.lineEdit_m_lastnamea = QtWidgets.QLineEdit(self.groupBox_m_modifya)
        self.lineEdit_m_lastnamea.setEnabled(False)
        self.lineEdit_m_lastnamea.setGeometry(QtCore.QRect(90, 20, 151, 20))
        self.lineEdit_m_lastnamea.setObjectName("lineEdit_m_lastnamea")
        self.lineEdit_m_firstnamea = QtWidgets.QLineEdit(self.groupBox_m_modifya)
        self.lineEdit_m_firstnamea.setEnabled(False)
        self.lineEdit_m_firstnamea.setGeometry(QtCore.QRect(260, 20, 151, 20))
        self.lineEdit_m_firstnamea.setText("")
        self.lineEdit_m_firstnamea.setObjectName("lineEdit_m_firstnamea")
        self.lineEdit_m_middlenamea = QtWidgets.QLineEdit(self.groupBox_m_modifya)
        self.lineEdit_m_middlenamea.setEnabled(False)
        self.lineEdit_m_middlenamea.setGeometry(QtCore.QRect(430, 20, 151, 20))
        self.lineEdit_m_middlenamea.setObjectName("lineEdit_m_middlenamea")
        self.lineEdit_m_programa = QtWidgets.QLineEdit(self.groupBox_m_modifya)
        self.lineEdit_m_programa.setEnabled(False)
        self.lineEdit_m_programa.setGeometry(QtCore.QRect(150, 80, 111, 20))
        self.lineEdit_m_programa.setPlaceholderText("")
        self.lineEdit_m_programa.setObjectName("lineEdit_m_programa")
        self.lineEdit_m_emailaddress = QtWidgets.QLineEdit(self.groupBox_m_modifya)
        self.lineEdit_m_emailaddress.setEnabled(False)
        self.lineEdit_m_emailaddress.setGeometry(QtCore.QRect(150, 140, 201, 20))
        self.lineEdit_m_emailaddress.setObjectName("lineEdit_m_emailaddress")
        self.lineEdit_m_contactnumbera = QtWidgets.QLineEdit(self.groupBox_m_modifya)
        self.lineEdit_m_contactnumbera.setEnabled(False)
        self.lineEdit_m_contactnumbera.setGeometry(QtCore.QRect(150, 110, 111, 20))
        self.lineEdit_m_contactnumbera.setPlaceholderText("")
        self.lineEdit_m_contactnumbera.setObjectName("lineEdit_m_contactnumbera")
        self.lineEdit_m_address1 = QtWidgets.QLineEdit(self.groupBox_m_modifya)
        self.lineEdit_m_address1.setEnabled(False)
        self.lineEdit_m_address1.setGeometry(QtCore.QRect(150, 170, 61, 20))
        self.lineEdit_m_address1.setObjectName("lineEdit_m_address1")
        self.lineEdit_m_address2 = QtWidgets.QLineEdit(self.groupBox_m_modifya)
        self.lineEdit_m_address2.setEnabled(False)
        self.lineEdit_m_address2.setGeometry(QtCore.QRect(220, 170, 131, 20))
        self.lineEdit_m_address2.setObjectName("lineEdit_m_address2")
        self.lineEdit_m_address3 = QtWidgets.QLineEdit(self.groupBox_m_modifya)
        self.lineEdit_m_address3.setEnabled(False)
        self.lineEdit_m_address3.setGeometry(QtCore.QRect(360, 170, 141, 20))
        self.lineEdit_m_address3.setObjectName("lineEdit_m_address3")
        self.lineEdit_m_address4 = QtWidgets.QLineEdit(self.groupBox_m_modifya)
        self.lineEdit_m_address4.setEnabled(False)
        self.lineEdit_m_address4.setGeometry(QtCore.QRect(150, 200, 131, 20))
        self.lineEdit_m_address4.setObjectName("lineEdit_m_address4")
        self.lineEdit_m_address5 = QtWidgets.QLineEdit(self.groupBox_m_modifya)
        self.lineEdit_m_address5.setEnabled(False)
        self.lineEdit_m_address5.setGeometry(QtCore.QRect(290, 200, 131, 20))
        self.lineEdit_m_address5.setObjectName("lineEdit_m_address5")
        self.lineEdit_m_address6 = QtWidgets.QLineEdit(self.groupBox_m_modifya)
        self.lineEdit_m_address6.setEnabled(False)
        self.lineEdit_m_address6.setGeometry(QtCore.QRect(430, 200, 131, 20))
        self.lineEdit_m_address6.setObjectName("lineEdit_m_address6")
        self.email_panel = QtWidgets.QGroupBox(Dialog)
        self.email_panel.setGeometry(QtCore.QRect(140, 90, 651, 451))
        self.email_panel.setTitle("")
        self.email_panel.setObjectName("email_panel")
        self.pushButton_e_send = QtWidgets.QPushButton(self.email_panel)
        self.pushButton_e_send.setEnabled(True)
        self.pushButton_e_send.setGeometry(QtCore.QRect(290, 370, 81, 31))
        self.pushButton_e_send.setObjectName("pushButton_e_send")
        self.lineEdit_e_subject = QtWidgets.QLineEdit(self.email_panel)
        self.lineEdit_e_subject.setGeometry(QtCore.QRect(90, 60, 521, 20))
        self.lineEdit_e_subject.setObjectName("lineEdit_e_subject")
        self.textEdit_e_body = QtWidgets.QTextEdit(self.email_panel)
        self.textEdit_e_body.setGeometry(QtCore.QRect(40, 120, 571, 241))
        self.textEdit_e_body.setObjectName("textEdit_e_body")
        self.xx_39 = QtWidgets.QLabel(self.email_panel)
        self.xx_39.setGeometry(QtCore.QRect(40, 60, 71, 16))
        self.xx_39.setObjectName("xx_39")
        self.xx_40 = QtWidgets.QLabel(self.email_panel)
        self.xx_40.setGeometry(QtCore.QRect(40, 100, 41, 16))
        self.xx_40.setObjectName("xx_40")
        self.xx_38 = QtWidgets.QLabel(self.email_panel)
        self.xx_38.setGeometry(QtCore.QRect(40, 30, 161, 16))
        self.xx_38.setObjectName("xx_38")
        self.ve_panel = QtWidgets.QGroupBox(Dialog)
        self.ve_panel.setGeometry(QtCore.QRect(140, 90, 651, 451))
        self.ve_panel.setTitle("")
        self.ve_panel.setObjectName("ve_panel")
        self.pushButton_ve_view = QtWidgets.QPushButton(self.ve_panel)
        self.pushButton_ve_view.setEnabled(True)
        self.pushButton_ve_view.setGeometry(QtCore.QRect(280, 230, 81, 31))
        self.pushButton_ve_view.setObjectName("pushButton_ve_view")
        self.dateEdit_ve = QtWidgets.QDateEdit(self.ve_panel)
        self.dateEdit_ve.setGeometry(QtCore.QRect(292, 178, 121, 22))
        self.dateEdit_ve.setMaximumDate(QtCore.QDate(7999, 12, 31))
        self.dateEdit_ve.setMinimumDate(QtCore.QDate(2018, 1, 1))
        self.dateEdit_ve.setObjectName("dateEdit_ve")
        self.xx_41 = QtWidgets.QLabel(self.ve_panel)
        self.xx_41.setGeometry(QtCore.QRect(240, 180, 51, 16))
        self.xx_41.setObjectName("xx_41")
        self.xx_42 = QtWidgets.QLabel(self.ve_panel)
        self.xx_42.setGeometry(QtCore.QRect(240, 150, 171, 16))
        self.xx_42.setObjectName("xx_42")
        self.hide_panels()
        self.vsi_panel.setVisible(True)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_viewSessionLog.setText(_translate("Dialog", "View\n"
"Session Log"))
        self.pushButton_viewTimeSheetLog.setText(_translate("Dialog", "View\n"
"Timesheet Log"))
        self.pushButton_add.setText(_translate("Dialog", "Add"))
        self.pushButton_modify.setText(_translate("Dialog", "Modify"))
        self.pushButton_clearDatabase.setText(_translate("Dialog", "Clear Database"))
        self.pushButton_email.setText(_translate("Dialog", "Email"))
        self.pushButton_viewEvaluation.setText(_translate("Dialog", "View\n"
"Evaluation"))
        self.label_adminPanel.setText(_translate("Dialog", "Admin Panel"))
        self.pushButton_viewStudentInfo.setText(_translate("Dialog", "View\n"
"Student Info"))
        self.radioButton_vsi_advisee.setText(_translate("Dialog", "Advisee"))
        self.radioButton_vsi_peeradviser.setText(_translate("Dialog", "Peer Adviser"))
        self.lineEdit_vsi_studentnumber.setPlaceholderText(_translate("Dialog", "Student Number"))
        self.pushButton_vsi_search.setText(_translate("Dialog", "Search"))
        self.groupBox_vsia.setTitle(_translate("Dialog", "Student Information"))
        self.xx_3.setText(_translate("Dialog", "Home Address:"))
        self.xx.setText(_translate("Dialog", "Name:"))
        self.xx_2.setText(_translate("Dialog", "Program:"))
        self.xx_4.setText(_translate("Dialog", "Email Address:"))
        self.xx_5.setText(_translate("Dialog", "Contact Number:"))
        self.groupBox_vsip.setTitle(_translate("Dialog", "Student Information"))
        self.xx_7.setText(_translate("Dialog", "Name:"))
        self.xx_8.setText(_translate("Dialog", "Program:"))
        self.xx_9.setText(_translate("Dialog", "Organization:"))
        self.xx_10.setText(_translate("Dialog", "Contact Number:"))
        self.xx_11.setText(_translate("Dialog", "Advising Schedule:"))
        self.pushButton_vsi_delete.setText(_translate("Dialog", "Delete User"))
        self.radioButton_vsl_searchByDate.setText(_translate("Dialog", "Search by date"))
        self.radioButton_vsl_searchByStudentNumber.setText(_translate("Dialog", "Search by student number"))
        self.lineEdit_vsl_studentnumber.setPlaceholderText(_translate("Dialog", "Student Number"))
        self.pushButton_vsl_search.setText(_translate("Dialog", "Search"))
        item = self.tableWidget_vslbsn.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Date"))
        item = self.tableWidget_vslbsn.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Time in"))
        item = self.tableWidget_vslbsn.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Time out"))
        item = self.tableWidget_vslbsn.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Subject"))
        item = self.tableWidget_vslbsn.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Peer Adviser"))
        item = self.tableWidget_vslbd.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Student Number"))
        item = self.tableWidget_vslbd.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Time in"))
        item = self.tableWidget_vslbd.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Time out"))
        item = self.tableWidget_vslbd.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Subject"))
        item = self.tableWidget_vslbd.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Peer Adviser"))
        self.radioButton_vts_searchByDate.setText(_translate("Dialog", "Search by date"))
        self.radioButton_vts_searchByStudentNumber.setText(_translate("Dialog", "Search by student number"))
        self.lineEdit_vts_studentnumber.setPlaceholderText(_translate("Dialog", "Student Number"))
        self.pushButton_vts_search.setText(_translate("Dialog", "Search"))
        item = self.tableWidget_vtsbsn.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Date"))
        item = self.tableWidget_vtsbsn.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Time in"))
        item = self.tableWidget_vtsbsn.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Time out"))
        item = self.tableWidget_vtsbd.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Student Number"))
        item = self.tableWidget_vtsbd.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Time in"))
        item = self.tableWidget_vtsbd.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Time out"))
        self.radioButton_a_peeradviser.setText(_translate("Dialog", "Peer Adviser"))
        self.radioButton_a_admin.setText(_translate("Dialog", "Admin"))
        self.pushButton_a_register.setText(_translate("Dialog", "Register"))
        self.radioButton_a_advisee.setText(_translate("Dialog", "Advisee"))
        self.xx_26.setText(_translate("Dialog", "Choose a user type to register:"))
        self.radioButton_m_peeradviser.setText(_translate("Dialog", "Peer Adviser"))
        self.pushButton_m_confirm.setText(_translate("Dialog", "Confirm"))
        self.radioButton_m_advisee.setText(_translate("Dialog", "Advisee"))
        self.xx_27.setText(_translate("Dialog", "Current student number:"))
        self.lineEdit_m_currentstudentnumber.setPlaceholderText(_translate("Dialog", "Student Number"))
        self.checkBox_m_studentnumberp.setText(_translate("Dialog", "Student Number"))
        self.checkBox_m_namep.setText(_translate("Dialog", "Name"))
        self.checkBox_m_programp.setText(_translate("Dialog", "Program"))
        self.checkBox_m_organizationp.setText(_translate("Dialog", "Organization"))
        self.checkBox_m_contactnumberp.setText(_translate("Dialog", "Contact Number"))
        self.lineEdit_m_studentnumberp.setPlaceholderText(_translate("Dialog", "Student Number"))
        self.checkBox_m_advisingschedule.setText(_translate("Dialog", "Advising Schedule"))
        self.lineEdit_m_lastnamep.setPlaceholderText(_translate("Dialog", "Last Name"))
        self.lineEdit_m_firstnamep.setPlaceholderText(_translate("Dialog", "Given Name"))
        self.lineEdit_m_middlenamep.setPlaceholderText(_translate("Dialog", "Middle Name"))
        self.comboBox_m_day1.setItemText(0, _translate("Dialog", "Monday"))
        self.comboBox_m_day1.setItemText(1, _translate("Dialog", "Tuesday"))
        self.comboBox_m_day1.setItemText(2, _translate("Dialog", "Wednesday"))
        self.comboBox_m_day1.setItemText(3, _translate("Dialog", "Thursday"))
        self.comboBox_m_day1.setItemText(4, _translate("Dialog", "Friday"))
        self.comboBox_m_day1.setItemText(5, _translate("Dialog", "Saturday"))
        self.comboBox_m_time1.setItemText(0, _translate("Dialog", "7:30-9:00"))
        self.comboBox_m_time1.setItemText(1, _translate("Dialog", "9:00-10:30"))
        self.comboBox_m_time1.setItemText(2, _translate("Dialog", "10:30-12:00"))
        self.comboBox_m_time1.setItemText(3, _translate("Dialog", "12:00-13:30"))
        self.comboBox_m_time1.setItemText(4, _translate("Dialog", "13:30-15:00"))
        self.comboBox_m_time1.setItemText(5, _translate("Dialog", "15:00-16:30"))
        self.comboBox_m_time1.setItemText(6, _translate("Dialog", "16:30-18:00"))
        self.comboBox_m_time1.setItemText(7, _translate("Dialog", "18:00-19:30"))
        self.comboBox_m_time1.setItemText(8, _translate("Dialog", "19:30-21:00"))
        self.comboBox_m_day2.setItemText(0, _translate("Dialog", "Monday"))
        self.comboBox_m_day2.setItemText(1, _translate("Dialog", "Tuesday"))
        self.comboBox_m_day2.setItemText(2, _translate("Dialog", "Wednesday"))
        self.comboBox_m_day2.setItemText(3, _translate("Dialog", "Thursday"))
        self.comboBox_m_day2.setItemText(4, _translate("Dialog", "Friday"))
        self.comboBox_m_day2.setItemText(5, _translate("Dialog", "Saturday"))
        self.comboBox_m_time2.setItemText(0, _translate("Dialog", "7:30-9:00"))
        self.comboBox_m_time2.setItemText(1, _translate("Dialog", "9:00-10:30"))
        self.comboBox_m_time2.setItemText(2, _translate("Dialog", "10:30-12:00"))
        self.comboBox_m_time2.setItemText(3, _translate("Dialog", "12:00-13:30"))
        self.comboBox_m_time2.setItemText(4, _translate("Dialog", "13:30-15:00"))
        self.comboBox_m_time2.setItemText(5, _translate("Dialog", "15:00-16:30"))
        self.comboBox_m_time2.setItemText(6, _translate("Dialog", "16:30-18:00"))
        self.comboBox_m_time2.setItemText(7, _translate("Dialog", "18:00-19:30"))
        self.comboBox_m_time2.setItemText(8, _translate("Dialog", "19:30-21:00"))
        self.checkBox_m_studentnumbera.setText(_translate("Dialog", "Student Number"))
        self.checkBox_m_namea.setText(_translate("Dialog", "Name"))
        self.checkBox_m_programa.setText(_translate("Dialog", "Program"))
        self.checkBox_m_emailaddressa.setText(_translate("Dialog", "Mymail Address"))
        self.checkBox_m_contactnumbera.setText(_translate("Dialog", "Contact Number"))
        self.lineEdit_m_studentnumbera.setPlaceholderText(_translate("Dialog", "Student Number"))
        self.checkBox_m_homeaddress.setText(_translate("Dialog", "Home Address"))
        self.lineEdit_m_lastnamea.setPlaceholderText(_translate("Dialog", "Last Name"))
        self.lineEdit_m_firstnamea.setPlaceholderText(_translate("Dialog", "Given Name"))
        self.lineEdit_m_middlenamea.setPlaceholderText(_translate("Dialog", "Middle Name"))
        self.lineEdit_m_emailaddress.setPlaceholderText(_translate("Dialog", "someone@mymail.mapua.edu.ph"))
        self.lineEdit_m_address1.setPlaceholderText(_translate("Dialog", "No."))
        self.lineEdit_m_address2.setPlaceholderText(_translate("Dialog", "Street"))
        self.lineEdit_m_address3.setPlaceholderText(_translate("Dialog", "Barangay"))
        self.lineEdit_m_address4.setPlaceholderText(_translate("Dialog", "Town"))
        self.lineEdit_m_address5.setPlaceholderText(_translate("Dialog", "City"))
        self.lineEdit_m_address6.setPlaceholderText(_translate("Dialog", "State"))
        self.pushButton_e_send.setText(_translate("Dialog", "Send"))
        self.xx_39.setText(_translate("Dialog", "Subject:"))
        self.xx_40.setText(_translate("Dialog", "Body"))
        self.xx_38.setText(_translate("Dialog", "Recipient: All advisees"))
        self.pushButton_ve_view.setText(_translate("Dialog", "View"))
        self.dateEdit_ve.setDisplayFormat(_translate("Dialog", "M/yyyy"))
        self.xx_41.setText(_translate("Dialog", "MM/YYYY:"))
        self.xx_42.setText(_translate("Dialog", "View evaluation for:"))

    def connect_session(self, session):
        self.ses = session
        self.admin = self.ses.admin

    def hide_panels(self):
        self.vsi_panel.setVisible(False)
        self.vsl_panel.setVisible(False)
        self.vts_panel.setVisible(False)
        self.add_panel.setVisible(False)
        self.modify_panel.setVisible(False)
        self.email_panel.setVisible(False)
        self.ve_panel.setVisible(False)
        
    #View Student Information Panel Functions
    
    def vsi_clear(self):
        self.label_vsia_name.clear()
        self.label_vsia_program.clear()
        self.label_vsia_contactnumber.clear()
        self.label_vsia_homeaddress.clear()
        self.label_vsia_emailaddress.clear()
        self.label_vsip_name.clear()
        self.label_vsip_program.clear()
        self.label_vsip_organization.clear()
        self.label_vsip_contactnumber.clear()
        self.label_vsip_advisingschedule_1.clear()
        self.label_vsip_advisingschedule_2.clear()
    
    def push_vsi(self):
        self.hide_panels()
        self.vsi_panel.setVisible(True)
        self.radioButton_vsi_advisee.setChecked(True)
        self.groupBox_vsip.setVisible(False)
        self.lineEdit_vsi_studentnumber.clear()
        self.vsi_clear()
        
    def toggle_vsia(self):
        if self.radioButton_vsi_advisee.isChecked():
            self.groupBox_vsia.setVisible(True)      
        else:
            self.groupBox_vsia.setVisible(False) 
    
    def toggle_vsip(self):
        if self.radioButton_vsi_peeradviser.isChecked():
            self.groupBox_vsip.setVisible(True)      
        else:
            self.groupBox_vsip.setVisible(False) 
        
    def push_vsi_search(self):
        studentnumber = self.lineEdit_vsi_studentnumber.text()
        if self.radioButton_vsi_advisee.isChecked():
            if self.ses.get_advisee(studentnumber) != None:
                adv = Advisee(*self.ses.get_advisee(studentnumber))
                self.label_vsia_name.setText(adv.get_fullname())
                self.label_vsia_program.setText(adv.program)
                self.label_vsia_contactnumber.setText(adv.contactnumber)
                self.label_vsia_homeaddress.setText(adv.homeaddress)
                self.label_vsia_emailaddress.setText(adv.emailaddress)
            else:
                self.vsi_clear()
                self.smsg("Error: Student not found.")
        else:
            if self.ses.get_peeradviser(studentnumber) != None:
                padv = PeerAdviser(*self.ses.get_peeradviser(studentnumber))
                self.label_vsip_name.setText(padv.get_fullname())
                self.label_vsip_program.setText(padv.program)
                self.label_vsip_organization.setText(padv.program)
                self.label_vsip_contactnumber.setText(padv.contactnumber)
                self.label_vsip_advisingschedule_1.setText(padv.get_schedule()[0])
                self.label_vsip_advisingschedule_2.setText(padv.get_schedule()[1])
            else:
                self.vsi_clear()
                self.smsg("Error: Student not found.")
            
    
    
    #View Session Log Panel Functions
        
    def push_vsl(self):
        self.hide_panels()
        self.vsl_panel.setVisible(True)
        
    #View Timesheet Log Panel Functions
        
    def push_vts(self):
        self.hide_panels()
        self.vts_panel.setVisible(True)
        
    #Add user panel functions
        
    def push_add(self):
        self.hide_panels()
        self.add_panel.setVisible(True)
        
    #Modify user panel functions
        
    def push_modify(self):
        self.hide_panels()
        self.modify_panel.setVisible(True)
        
    #Send email panel functions
        
    def push_email(self):
        self.hide_panels()
        self.email_panel.setVisible(True)
        
    #View evaulation panel functions
        
    def push_ve(self):
        self.hide_panels()
        self.ve_panel.setVisible(True)



    #############
    
    def smsg(self, message):
        msg = QtWidgets.QMessageBox()
        msg.setWindowTitle('TutorialOn')
        #icon = QtGui.QIcon("TutorialOn.png")
        #msg.setWindowIcon(icon)
        msg.setText(message)
        msg.exec_()
        
        
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_AdminPanel()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

